### ISSUE TITLE
Internal links in RTE use incorrect link format (t3://page?uid=215)

### ISSUE THREAD

**Issue by OlenaBulat** [FriendsOfTYPO3/frontend_editing#403] opened 2020-01-29 10:05 UTC
Internal links in RTE use link format t3://page?uid=215 even if you are not logged in (this has previously only appeared when logged in).
![Screenshot_5](https://user-images.githubusercontent.com/26138552/73346997-89ed2c80-428f-11ea-97db-3801a1d27586.png)

**Comment by kevinandrewsde** [comment] 2020-01-30 14:02
I was able to solve this by changing the order in which the templates are included in the maintemplate.

**Comment by mabolek** [comment] 2020-02-03 09:25
@OlenaBulat Does Kevin's solution work for you? The Frontend Editing TypoScript template should be included last.

**Comment by erredeco** [comment] 2020-02-04 09:21
> I was able to solve this by changing the order in which the templates are included in the maintemplate.

@kevinandrewsde  which order did you use?

**Comment by kevinandrewsde** [comment] 2020-02-04 11:37
I was forced to include frontend_editing before any other templates in order for #403 and #405 to work

**Comment by vmans** [comment] 2020-02-29 13:20
I have the same issue as @OlenaBulat. Using TYPO3 10.2.2 (and 10.3.0 too) and frontend_editing 1.9.1.

The order of the templates doesn't matter. I actually have to uninstall frontend_editing to get things going again.

**Comment by anjeylink** [comment] 2020-03-05 06:39
@mabolek links in RTE doesn't work because BE user login condition `[globalVar = TSFE : beUserLogin > 0]` was removed from setup.ts, so now parsing of A tag is always disabled by `lib.parseFunc_RTE.tags.a >`

We should add BE login check back. For TYPO3 9 and 10 it would be `[getTSFE().isBackendUserLoggedIn()]`, I don't know if it's possible to keep compatibility with TYPO3 8 here.

**Comment by mabolek** [comment] 2020-03-05 07:55
Hi @anjeylink! PR #410 implements a fix for this with compatibility with TYPO3 versions 8, 9, and 10. However, we have gotten feedback that it might not work as expected. If you have the possibility, please feel free to test it and see how it works on your sites. 😃

**Closed** 2020-03-13 16:18 UTC
Labels: need info

**Comment by lorenzulrich** [comment] 2020-12-21 15:39
As I already commented in 2018 in https://github.com/FriendsOfTYPO3/frontend_editing/commit/f476b651406ca94768388e16be8d453fdaeeffc1#commitcomment-31188676, the problem here is that you assume that someone who has Frontend Editing installed will always work with Frontend Editing enabled. While FE Editing apparently needs Parsing of Links to be disabled, it should not be disabled if someone is logged in without have FE Editing active.

**Comment by mabolek** [comment] 2020-12-21 19:49
Hi @lorenzulrich! I wouldn't say that we assume that. The pull request that contains a fix to exactly that issue has been waiting for someone to confirm that it fixes another issue for some time.

If you'd like to check it out, take a look at PR #423. It fixes issue #405, but also adds a condition that should fix your issue too.

**Comment by lorenzulrich** [comment] 2020-12-21 20:37
Hi @mabolek 
Sorry if I was not clear - I meant: Looking at the current code base the extension assumes that everyone has FE editing enabled. Thanks for pointing me to the fix improving this behaviour. I will test and give feedback!

**Comment by lorenzulrich** [comment] 2020-12-21 20:56
@mabolek: I can confirm that the PR works in TYPO3 10.4. Thanks for taking care!

**Comment by mabolek** [comment] 2020-12-22 07:01
@lorenzulrich Thank you, that's excellent! I'll merge it at once.
