### ISSUE TITLE
Element tab missing from start page/subpage

### ISSUE THREAD

**Issue by mesosa** [FriendsOfTYPO3/frontend_editing#263] opened 2017-12-01 14:30 UTC
When on start page I am missing the second tab (Content Elements) from the content element tab from backend, and when I am on a subpage I am getting the second tab but missing the third one (Forms Elements).
When on startpage the third tab is visible but the second tab is missing:
![startpage](https://user-images.githubusercontent.com/4276194/33487002-33a992c4-d6ac-11e7-85b8-aaeed079637e.png)

When on a subpage the second tab is visible, but the third tab is missing:
![subpage](https://user-images.githubusercontent.com/4276194/33487097-73e36ec8-d6ac-11e7-96a4-ed0221763218.png)

View from the backend:
![be](https://user-images.githubusercontent.com/4276194/33485061-45f5d458-d6a5-11e7-84fe-393ed50d45c6.png)

**Comment by tim9413** [comment] 2017-12-07 12:54
Fixed with commit: https://github.com/FriendsOfTYPO3/frontend_editing/commit/735fc11f5c1e67306237b140f817af8786808ae2

**Comment by mabolek** [comment] 2019-06-23 10:25
Hi @mesosa!

Regarding part 2: The element is missing due to a condition in `EXT:felogin/ext_localconf.php`. By limiting the wizard PageTS to Backend only, the content element type will not be listed in the frontend, and thus not in the Frontend Editor. 

*I am closing this issue as the cause is external.*

I have opened tickets about this here. Please feel free to upvote and comment.

- felogin: https://forge.typo3.org/issues/88617
- form: https://forge.typo3.org/issues/88618

**Closed by mabolek** 2019-06-23 10:25 UTC
Labels: bug
