### ISSUE TITLE
Do not reload the page when no changes have been performed

### ISSUE THREAD

**Issue by Gloumi** [FriendsOfTYPO3/frontend_editing#252] opened 2017-09-26 12:42 UTC
This is frustrating for the user to have a page reload after closing the edit modal box without having made any changes.
In a more general way, I think the entire page reload degrades the user experience.

**Comment by codesource** [comment] 2017-09-26 13:06
+1 with both remarks

**Comment by pxamike** [comment] 2017-10-06 13:24
The problem is how to communicate this from the iframe in the modal back to the frontend editor. It also has to work on different site roots (iframe may have a different domain).

**Comment by webian** [comment] 2018-03-05 12:33
Duplicate of #214

**Closed** 2022-10-19 11:41 UTC
Labels: feature
