### ISSUE TITLE
Feature: integrate frontend_editing inside the backend

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#191] opened 2017-06-13 13:09 UTC
Add the possibility to have a module that integrates frontend_editing inside the backend with these advantages:
- one single url (domain.ext/typo3) for login and edit
- one single ambient (the BE) for edit content and do other actions
- "Page tree" already available with all the actions already implemented
- BE modules one click away

Administrator could have the possibility to configure if frontend editing will take place in FE and/or in BE module. Or we could go all the way to allow frontend editing only inside the BE.

Here is an example of how the UI could look like (the BE module has a pencil as icon).

![](https://i.imgur.com/Y24Yq1y.jpg)

**Comment by MattiasNilsson** [comment] 2018-10-30 16:07
The frontend editing are done in the frontend.

**Comment by webian** [comment] 2018-10-31 08:29
Hi @MattiasNilsson!
I see that you closed this feature request but your reason doesn't make sense to me so maybe it wasn't clear enough.

This idea is to bring the frontend editing inside the BE. See it as a View Module with editing functionality.

So the editor can make all his tasks in a single place: the backend. So by instance the editor can: search for records; manage schedules; use the list module; etc... but he/she can also edit the frontend without leaving the backend and **without learning a new UI**.

Another big advantage is that the **frontend editing can use the actual BE page tree** with all it's functionality. There's no need to re-create all its functionality (drag&drop; copy/paste; history management; etc...)

If it's more clear now, can you please re-open this feature request so it doesn't get buried?

**Comment by codesource** [comment] 2018-10-31 08:57
Hi @webian 

I see what you mean but I am agree with @MattiasNilsson, we should keep frontend editing in frontend.
There is many reasons about that:

- Editors that will use frontend editing will most of the time have no clue of what is TYPO3 Backend
- This will makes a duplicate of "Page" + "View" module.
- New editors are sometime afraid by TYPO3 Backend and all his functionalities, with frontend editing there is less thing to learn.

I think this feature should be done in an other extension, this is not that hard to make a module that call the current page in a frontend editing view. 

Kind regards

**Comment by kaystrobach** [comment] 2020-06-17 07:56
I also agree, that we should reuse the modules, that we already have like the pagetree. I also just see the FE Editing just as different representation of the Pagemodule, while it is technically way more complex.

**Comment by kaystrobach** [comment] 2020-06-17 07:58
Maybe we should hide the page tree and just display the outer frame (modules etc.) if the editor has just minor permissions, than most of the backend is hidden anyway.

I also see the benefits for atleast 2 customers here.

**Comment by MattiasNilsson** [comment] 2020-10-29 06:54
The foundation for this is already in place so closing it.

**Closed by MattiasNilsson** 2020-10-29 06:54 UTC
Labels: feature

**Comment by webian** [comment] 2020-10-29 07:18
Ok, but one usually closes an issue when it is solved, not when working on it.
