### ISSUE TITLE
Content move doesn't work

### ISSUE THREAD

**Issue by Oktopuce** [FriendsOfTYPO3/frontend_editing#126] opened 2017-01-23 12:24 UTC
When I moved a content up or down most of time that doesn't work although a message said that the content is moved.

**Comment by MattiasNilsson** [comment] 2017-01-23 12:27
Could you provide a more detailed use case? In fluid? In typoscript rendered content elements? Maybe provide some screenshots?

**Comment by Oktopuce** [comment] 2017-01-23 13:44
In the fe edition when I try to move a content up or down (see screenshot).

![frontend-edit](https://cloud.githubusercontent.com/assets/7236405/22206007/a69e5c84-e179-11e6-96f3-824850f1fc5d.jpg)

It seems to happen all the time with the first content element that you can only move down and which never moves down.

![first content](https://cloud.githubusercontent.com/assets/7236405/22206152/5b3f8da2-e17a-11e6-9fb9-3034516ba72b.jpg)

**Comment by MattiasNilsson** [comment] 2017-01-23 13:56
Thanks for the feedback 👍

**Comment by pascal20997** [comment] 2017-03-15 14:59
I can´t reproduce this issue with version 8.7.0. Can you try to reproduce this with the latest version? I think this bug is already fixed.

**Comment by MattiasNilsson** [comment] 2017-04-05 05:42
After no answer in a couple of weeks and it´s fixed since the first release. I will close this ticket.

**Closed by MattiasNilsson** 2017-04-05 05:42 UTC
