### ISSUE TITLE
Inline Frontend Editing broken when text contains a link

### ISSUE THREAD

**Issue by cozr** [FriendsOfTYPO3/frontend_editing#305] opened 2018-10-09 16:03 UTC
There are two ways of frontend-editing: 
# the „inline“ one, using the frontend-editing bar in the top 
# using the pencil symbol which opens a new „window“

Using the first variant („inline“) is not possible if the text contains a link. When clicking the „Save all“-Button it crashes with an „Uncaught TYPO3 Exception”( Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1460629247: No valid handlers found for type: unknown | TYPO3\CMS\Core\LinkHandling\Exception\UnknownLinkHandlerException thrown in file /usr/share/typo3/typo3_src-8.7.19/typo3/sysext/core/Classes/LinkHandling/LinkService.php in line 163. Requested URL: https://www.xxx.de/typo3/index.php?ajaxID=%2Fajax%2Ffrontend-editing%2Fprocess&ajaxToken=--AnonymizedToken--&page=528  

Creating a link is possible - also in the inline variant: it's possible to save but it not possible to change anything after the first save. Clicking a second time on save the same error as mentioned above appears.

PS: If it is important: I'm using css_styeled_content
PSS: I also created  bug report here: https://forge.typo3.org/issues/86607

**Comment by tripbe** [comment] 2018-10-10 20:56
Duplicate of #220 
@devtroll provided a snippet for a hook
 https://bitbucket.org/snippets/scw_bihlmaier/5ezpaB
for TYPO3 9.5 with new Url-Routing the Query needs to be changed 
```php
$queryBuilder = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Database\ConnectionPool::class)->getQueryBuilderForTable('pages');
                $page = $queryBuilder
                    ->select('uid')
                    ->from('pages')
                    ->where(
                        $queryBuilder->expr()->eq('slug', $queryBuilder->createNamedParameter($wrong))
                    )
                    ->execute()
                    ->fetchColumn(0);
```

**Comment by cozr** [comment] 2018-10-11 09:27
Hello tripbe,

sorry, I'm not very experienced in TYPO3: We use TYPO3 8.7.19. In which file do I have to do the above mentioned changes?

**Comment by ademas02** [comment] 2018-10-15 12:36
Hi. In my project I observed that only internal links are producing this error, external not.

**Comment by cozr** [comment] 2018-10-15 13:02
I can confirm: only internal links are affected

**Closed** 2018-10-17 10:50 UTC
