### ISSUE TITLE
Unable to edit HERO Image element

### ISSUE THREAD

**Issue by viacheslavresultify** [FriendsOfTYPO3/frontend_editing#357] opened 2019-08-29 08:55 UTC
After adding the hero image we can't edit that. the edit popup just not apears

**Comment by mabolek** [comment] 2019-08-30 07:51
Hi @viacheslavresultify!

This is a duplicate of #349 

Please try to specify your issues in generic terms, without project-specific descriptions.

**Closed by mabolek** 2019-08-30 07:51 UTC
