### ISSUE TITLE
2 headings after saving

### ISSUE THREAD

**Issue by benzinkanister** [FriendsOfTYPO3/frontend_editing#330] opened 2019-03-27 13:19 UTC
After editing and saving a text-element, the heading will be inserted twice.

```
<h2>Test</h2>
<p>Text</p>
```

is saved to:

```
<h2>Test</h2>
<h2>Test</h2>
<p>Text Text</p>
```

In the backend the 2nd heading is placed in the bodytext-area.

**Comment by myroslav321** [comment] 2019-05-16 08:15
@benzinkanister Can't reproduce this issue, can you pls provide more information?

**Comment by mabolek** [comment] 2019-05-16 08:31
Possibly related to #304

**Comment by mabolek** [comment] 2019-08-30 08:02
I'm closing this issue as no further information has been provided by the reporter.

**Closed by mabolek** 2019-08-30 08:02 UTC
Labels: can't reproduce
