### ISSUE TITLE
the frontend editing disappears on pages that are targets of a shortcut page

### ISSUE THREAD

**Issue by erredeco** [FriendsOfTYPO3/frontend_editing#398] opened 2020-01-23 22:14 UTC
Version: 1.9.0
TYPO3 version: 9.5.13

How to reproduce: 

1) create a pagetree like this one

```
Home
 >[2] Shortcut page
     > [10] target page
     > [11] another page
```

[2] Shortcut page is a shortcut page with:
- `[shortcut_mode]`: Selected page
- `[shortcut]`: the target page (ID=10)

2) Enable frontend editing and visit the page 10 

Expected result: the "frame" with the content editing function is loaded

Actual result: you just see the page

If you visit the page "another page" (ID=11) instead it works.

**Comment by mabolek** [comment] 2020-01-24 07:49
Hi @erredeco!

Thank you for submitting this issue.

It looks like there might be an additional factor contributing to this issue. I was unable to reproduce it in the exact setup you mentioned, but I had the same issue on my site's root page (which is the target of a shortcut).

**Comment by erredeco** [comment] 2020-01-24 08:12
Hi and thanlks for the reply; actually I find that it  appears discontinuously, too. It seems related to the browser's cache, let's close it for now. I will open a new one if it comes again more consistently

**Comment by MattiasNilsson** [comment] 2021-02-08 06:38
I will close this as in frontend editing v2 it is a backend module that uses the TYPO3 page tree: https://github.com/FriendsOfTYPO3/frontend_editing/pull/434

**Closed by MattiasNilsson** 2021-02-08 06:38 UTC
Labels: bug, need info
